# STAGE 1 builder
FROM golang:latest
WORKDIR /app
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o server
#RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o server

# STAGE 2 runner
FROM scratch
COPY --from=0 /app/server /app/server

# Misc
EXPOSE 8080

# Start the server
ENTRYPOINT ["/app/server"]