FROM golang:latest as builder
WORKDIR /app
COPY . .

# run
RUN go mod tidy
RUN go build -o /go/bin/govatar-server .

FROM scratch
COPY --from=builder /go/bin/govatar-server /go/bin/govatar-server

# Misc
EXPOSE 8080

# Start the server
ENTRYPOINT ["/go/bin/govatar-server"]